name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run Linter
        uses: norio-nomura/action-swiftlint@master
  test:
    runs-on: macOS-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Pods
        run: |
        pod install --repo-update --clean-install
      - name: Build Workspace and Run Tests
        run: exec ./.github/scripts/test.sh
